---
name: release binary

on:
  release:
    types: [created]

jobs:
  release-alpine-static:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker compose
        run: STAKE_TOKEN="usaft" TIMEOUT_COMMIT=500ms docker compose up -d

      - name: Copy binary
        run: docker cp safrochain-node-1:/usr/bin/safrochaind ./safrochaind

      - name: Save sha256 sum
        run: sha256sum ./safrochaind > ./safrochaind_sha256.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          files: |
            safrochaind
            safrochaind_sha256.txt

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
